Zephia\OLXFeed\Entity\AdBag:
  access_type: public_method
  exclusion_policy: NONE
  properties:
    ads:
      type: "array<Zephia\\OLXFeed\\Entity\\Ad>"
      xml_list:
        entry_name: AD
        inline: true
  # Needs to be uppercase.
  xml_root_name: ADS
