Zephia\OLXFeed\Entity\Contact:
  access_type: public_method
  exclusion_policy: NONE
  properties:
    email:
      type: "string"
      serialized_name: "contact_email"
    name:
      type: "string"
      serialized_name: "contact_name"
    phone:
      type: "string"
      serialized_name: "contact_phone"
      xml_element:
        cdata: true
