Zephia\OLXFeed\Entity\AdBag:
  access_type: public_method
  exclusion_policy: NONE
  properties:
    vehicles:
      type: "array<Zephia\\OLXFeed\\Entity\\Ad>"
      xml_list:
        entry_name: ad
        inline: true
  xml_root_name: ads
